version: '3'

services:
  backend:
    container_name: 'backend'
    build:
      context: backend
      dockerfile: Dockerfile
    env_file: .env
    restart: unless-stopped
    ports:
      - '4000:3000'
    environment:
      DB_HOST: host.docker.internal
    depends_on:
      - postgres

  postgres:
    container_name: 'localhost'
    image: postgres:12.12-alpine
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file: .env
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata

  frontend:
    container_name: 'frontend'
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '8081:80'
volumes:
  pg_data:
    driver: local

networks:
  backend:
